//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlassdoorReviewsCollector.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.glassdoor.com/Reviews/index.htm")]
        public string homepage {
            get {
                return ((string)(this["homepage"]));
            }
            set {
                this["homepage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#KeywordSearch")]
        public string company_name_selector {
            get {
                return ((string)(this["company_name_selector"]));
            }
            set {
                this["company_name_selector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#LocationSearch")]
        public string location_selector {
            get {
                return ((string)(this["location_selector"]));
            }
            set {
                this["location_selector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#SrchHero > div > div.static-hph-hero-srch.acq-2414-home-cta-A > div.search-bar.m" +
            "inimized > div > form")]
        public string form_selector {
            get {
                return ((string)(this["form_selector"]));
            }
            set {
                this["form_selector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#HeroSearchButton")]
        public string search_button_selector {
            get {
                return ((string)(this["search_button_selector"]));
            }
            set {
                this["search_button_selector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".autocomplete-suggestions ")]
        public string autocomplete_divs_selector {
            get {
                return ((string)(this["autocomplete_divs_selector"]));
            }
            set {
                this["autocomplete_divs_selector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#LocationFilter")]
        public string results_locationSelector {
            get {
                return ((string)(this["results_locationSelector"]));
            }
            set {
                this["results_locationSelector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#MainCol > div:nth-child(1) > div:nth-child({i}) > div.empInfo.tbl > div.header.c" +
            "ell.info > div.margBotXs > a")]
        public string results_names {
            get {
                return ((string)(this["results_names"]));
            }
            set {
                this["results_names"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#MainCol > div:nth-child(1) > div:nth-child({i}) > div.empInfo.tbl > div.header.c" +
            "ell.info > div.showDesk.subtle > span.webInfo > span")]
        public string results_website {
            get {
                return ((string)(this["results_website"]));
            }
            set {
                this["results_website"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#MainCol > div:nth-child(1) > div:nth-child({i}) > div.empLinks.tbl.noswipe > spa" +
            "n > div > span:nth-child(1) > span.bigRating.strong.margRtSm.h1")]
        public string results_rating {
            get {
                return ((string)(this["results_rating"]));
            }
            set {
                this["results_rating"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FooterPageNav > div > ul > li.next > a")]
        public string results_nextPage {
            get {
                return ((string)(this["results_nextPage"]));
            }
            set {
                this["results_nextPage"] = value;
            }
        }
    }
}
